spring.application.name=sireclamations
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
management.endpoint.health.show-details=always
management.health.db.enabled=false
management.endpoint.health.status.http-mapping.down=500
management.endpoint.health.status.http-mapping.out_of_service=503
management.endpoint.health.status.http-mapping.warning=500
management.endpoints.web.base-path=/
referentiel.categorie.etablissement=classpath:data/sousCatFINESS-ac.csv
referentiel.autorite.contact=classpath:data/departements-ac-contacts.csv
referentiel.formulaire.type-mec=classpath:data/mappingFormulaireV2-typeMEC.csv
referentiel.autorite.type-mec=classpath:data/typeMEC-ac.csv
demat.social.graphql-endpoint=https://demat.social.gouv.fr/