spring.application.name=sireclamations
demat.social.graphql-endpoint=https://demat.social.gouv.fr/api/v2/graphql
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
management.endpoint.health.show-details=always
management.health.db.enabled=false
management.endpoint.health.status.http-mapping.down=500
management.endpoint.health.status.http-mapping.out_of_service=503
management.endpoint.health.status.http-mapping.warning=500
management.endpoints.web.base-path=/
