spring.application.name=sireclamations
management.endpoint.health.show-details=always
management.health.db.enabled=false
management.endpoint.health.status.http-mapping.down=500
management.endpoint.health.status.http-mapping.out_of_service=503
management.endpoint.health.status.http-mapping.warning=500
management.endpoints.web.base-path=/
referentiel.categorie.etablissement=classpath:data/sousCatFINESS-ac.csv
referentiel.autorite.contact=classpath:data/departements-ac-contacts.csv
referentiel.formulaire.champs=classpath:data/mappingFormulaireV2.csv
referentiel.formulaire.type-mec=classpath:data/mappingFormulaireV2-typeMEC.csv
referentiel.formulaire.type-lieux=classpath:data/mappingFormulaireV2-typeLieux.csv
referentiel.autorite.type-mec=classpath:data/typeMEC-ac.csv
demat.social.graphql-endpoint=https://demat.social.gouv.fr/
opendatasoft.base-url=https://arssante.opendatasoft.com/api/explore/v2.1/catalog/datasets/
management.endpoint.info.access=read_only
management.endpoints.web.exposure.include=health, info
management.info.git.enabled=true
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.org.springframework.boot.actuate=DEBUG
#logging.level.org.springframework=DEBUG